myshop/blog/urls.py
from django.urls import path
from . import views

app_name= "blog"

urlpatterns = [
    path("<slug:post_detail>/<int:year>/<int:month>/<int:day>/", views.postdetail, name="post_detail"),
    path("blog", views.postlist, name="blog_news")
]

myshop/cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),

    path('remove/<int:product_id>/', views.cart_remove, 
                                     name='cart_remove'),
                                     
    path('checkout', views.checkout, name='checkout'),
]

myshop/coupons/urls.py
from django.urls import path
from . import views
app_name = 'coupons'
urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

myshop/myonlineshop/urls.py
from django.urls import path
from . import views


app_name = 'myonlineshop'

urlpatterns = [
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('selectcurrency', views.selectcurrency, name='selectcurrency'),
    path('', views.index, name='index'),
    # path('', views.home, name='home'),
    path('selectcurrency', views.selectcurrency, name='selectcurrency'),
    path('picture_x', views.picture, name='picture'),
    path('contact', views.contact, name='contact'),
    path('checkout', views.checkout, name='checkout'),
    
    path('categorie', views.categorie, name='categorie'),
    path('search', views.post_search, name='post_search'),
    path('trackorder', views.track, name='track_order'),
    path('store', views.product_list, name='product_list'),
    path('addcomment/<int:id>', views.addcomment, name='addcomment'),
    path('mail', views.popMail, name='mail'),
    #path('addcomment/<int:id>', views.addcomment, name='addcomment'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    


]

myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
     path('currencies/', include('currencies.urls')),
    path('admin/', admin.site.urls),

    path('paystack/', include('paystack.urls', namespace='paystack')),


    path('cart/', include('cart.urls', namespace='cart')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('orders/', include('order.urls', namespace='order')),
    path('account/', include('account.urls')),

    path('payment/', include('payment.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('myonlineshop.urls', namespace='myonlineshop')),

    # path('about/', about),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

myshop/order/urls.py
from django.urls import path
from . import views
# from paystack.views import delete_order
app_name = 'orders'
urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    # path('myorder/<int:id>/<int:user_id>/', views.my_order, name='my_order'),
    path('allorders/', views.all_orders, name='all_order'),
    path('orderitem/<int:product_id>/<int:quantity>/<int:order_id>/<int:user_id>/', views.my_order, name='order_item'),
    path('admin/order/<int:order_id>/<int:user_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/',views.admin_order_pdf, name='admin_order_pdf'),
    path('delete/<int:id>/', views.delete, name='delete-person'),
    # path('deleteorder/<int:id>', views.delete_order, name='user_deleteorder'),
]

myshop/paystack/urls.py
from django.conf.urls import url
from django.views.decorators.csrf import csrf_exempt

from . import settings
from . import views

app_name = 'paystack'

urlpatterns = [
    url(r'^verify-payment/(?P<order>[\w.@+-]+)/$',
        views.verify_payment, name='verify_payment'),
    
    url(r'^failed-verification/(?P<order_id>[\w.@+-]+)/$',
        views.failure_redirect_view, name='failed_verification'),
    url(r'^successful-verification/(?P<order_id>[\w.@+-]+)/$', views.success_redirect_view,name='successful_verification'),
    url(r'^checkout/payment/$', views.payment, name='payment'),
    url(r'^failed-page/$',
        views.TemplateView.as_view(template_name='paystack/failed-page.html'), name='failed_page'),
    url(r'^success-page/$',
        views.success, name='success_page'),
    url(r'^delete/(?P<id>.*)$', views.delete, name='delete-person'),
    url(r'^webhook/$', csrf_exempt(views.webhook_view), name='webhook'),
]

myshop/cart/models.py
from django.db import models

# Create your models here.

myshop/cart/forms.py
from django import forms
PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 4)]
Size_choice = (
        
        ("None", "None"),
        ('S', 'Small'),
        ('L', 'Large'),
        ('XL', 'Extra Large'),
        ("39", "39"),
        ("40", "40"),
        ("41", "41"),
        ("42", "42")
        

)
class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int)
    override = forms.BooleanField(required=False, initial=False,widget=forms.HiddenInput)
    size_cloth = forms.TypedChoiceField(required=False, choices=Size_choice,  label="Size:", initial='ms')
class CartSizeAddProductForm(forms.Form):
        size_cloth = forms.TypedChoiceField(required=False, choices=Size_choice,  label="Size:", initial='ms')
   

myshop/cart/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from myonlineshop.models import Product
from .cart import Cart
from .forms import CartAddProductForm, CartSizeAddProductForm
from coupons.forms import CouponApplyForm
from django.contrib import messages
from django.http import HttpResponseRedirect
from myonlineshop.recommender import Recommender


@require_POST
def cart_add(request, product_id):
    url = request.META.get('HTTP_REFERER') #get last url
    
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    form_size = CartSizeAddProductForm(request.POST)
    
    
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'],
                 size_cloth= cd['size_cloth'])
                 

    # elif form_size.is_valid():
    #     md = form_size.cleaned_data
    #     cart.add(product=product,
    #              quantity=md['quantity'],
    #              override_quantity=md['override'],
    #              size_cloth= md['size_cloth'])

                 
        
    

 
    
                 
                 

    
    # return HttpResponseRedirect(url)
    return redirect('cart:cart_detail')
        
                 
    # return redirect('myonlineshop:product_detail')




@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
                            'quantity': item['quantity'],
                            'override': True}) 
    
                           

 
    coupon_apply_form = CouponApplyForm()   
    r = Recommender()
    # cart_products = [item['product'] for item in cart]
    # recommended_products = r.suggest_products_for(cart_products,
    #                                               max_results=4)                     
    return render(request, 'cart/detail.html', {'cart': cart, 'coupon_apply_form': coupon_apply_form})

def checkout(request):
    return render(request, 'cart/checkout.html', {})

myshop/cart/templates/cart/checkout.html
{% extends 'shop/base.html' %}

{% block content %}

<div class="card-warp" style="margin-top:120px; margin-bottom:40px;">
			<div class="container">
				<div class="row">
					<div class="col-lg-4">
						<div class="shipping-info">
							<h4>Shipping method</h4>
							<p>Select the one you want</p>
							<div class="shipping-chooes">
								<div class="sc-item">
									<input type="radio" name="sc" id="one">
									<label for="one">Next day delivery<span>$4.99</span></label>
								</div>
								<div class="sc-item">
									<input type="radio" name="sc" id="two">
									<label for="two">Standard delivery<span>$1.99</span></label>
								</div>
								<div class="sc-item">
									<input type="radio" name="sc" id="three">
									<label for="three">Personal Pickup<span>Free</span></label>
								</div>
							</div>
							<h4>Cupon code</h4>
							<p>Enter your cupone code</p>
							<div class="cupon-input">
								<input type="text">
								<button class="site-btn">Apply</button>
							</div>
						</div>
					</div>
					<div class="offset-lg-2 col-lg-6">
						<div class="cart-total-details">
							<h4>Cart total</h4>
							<p>Final Info</p>
							<ul class="cart-total-card">
								<li>Subtotal<span>$59.90</span></li>
								<li>Shipping<span>Free</span></li>
								<li class="total">Total<span>$59.90</span></li>
							</ul>
							<a class="site-btn btn-full" href="checkout">Proceed to checkout</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Page end -->

{% endblock  %}

myshop/cart/templates/cart/detail.html
{% extends 'shop/base.html' %}
{% load crispy_forms_tags %}
{% load currency %}
<!DOCTYPE html>
<html lang="zxx">
<head>
	<title>The Plaza - eCommerce Template</title>
	<meta charset="UTF-8">
	<meta name="description" content="The Plaza eCommerce Template">
	<meta name="keywords" content="plaza, eCommerce, creative, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Favicon -->
	<link href="img/favicon.ico" rel="shortcut icon"/>

	<!-- Google Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Raleway:400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

	<!-- Stylesheets -->
	<link rel="stylesheet" href="css/bootstrap.min.css"/>
	<link rel="stylesheet" href="css/font-awesome.min.css"/>
	<link rel="stylesheet" href="css/owl.carousel.css"/>
	<link rel="stylesheet" href="css/style.css"/>
	<link rel="stylesheet" href="css/animate.css"/>


	<!--[if lt IE 9]>
	  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>
<body>




    {% block content %}


	<!-- Page -->
<div class="container" style="margin-top:120px">
  <h2 class="mb-3">Your shopping cart</h2>

  <div class="table-responsive">
  <table  class="table table-striped">
    <thead >
      <tr>
        <th>Image</th>
        <th>Product</th>
        <th>Size</th>
        <th>Quantity</th>
        <th>Remove</th>
        <th>Unit price</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url }} {% else %}  http://localhost/external-css/img/no_image.png {% endif %}" class="img-thumbnail" width="100px" height="100px">
              </a>
            </td>
            <td>{{ product.name }}  </td>
            <td>{{item.size_cloth}}</td>

            <td>
                <form action="{% url "cart:cart_add" product.id %}" method="post">
                    {{ item.update_quantity_form.quantity }}
                    {{ item.update_quantity_form.override }}
                    <input type="submit" class="btn btn-success btn-sm" value="Update">
                    {% csrf_token %}
                </form>
                </td>

            <td>
              <form action="{% url "cart:cart_remove" product.id %}" method="post">
                <input type="submit" class="btn btn-success btn-sm" value="Remove">
                {% csrf_token %}
              </form>
            </td>

            <td class="num">{{ item.price|currency:request.session.currency }} {{ request.session.currency }}</td>
            <td class="num">{{ item.total_price|currency:request.session.currency }} {{ request.session.currency }} </td>
          </tr>
        {% endwith %}
      {% endfor %}
      {% if cart.coupon %}
  <tr class="subtotal">
    <td>Subtotal</td>
    <td colspan="4"></td>
    <td class="num">{{ cart.get_total_price|currency:request.session.currency }} {{ request.session.currency }}</td>
  </tr>
  <tr>
    <td>
      "{{ cart.coupon.code }}" coupon
      ({{ cart.coupon.discount }}% off)
    </td>
    <td colspan="4"></td>
    <td class="num neg">
      - {{ cart.get_discount|currency:request.session.currency }} {{ request.session.currency }}
      </td>
    </tr>
    {% endif %}
    <tr class="total">
      <td>Total</td>
      <td colspan="5"></td>
      <td class="num">
        {{ cart.get_total_price_after_discount|currency:request.session.currency }} {{ request.session.currency }}
      </td>
    </tr>
      </tbody>
    </table>

    <p>Apply a coupon:</p>
    <form action="{% url "coupons:apply" %}" method="post">
      {{ coupon_apply_form|crispy }}
      <input type="submit" value="Apply" class="btn btn-primary">
      {% csrf_token %}
    </form>

      <br>
      <p class="text-right">
      <a href="{% url "myonlineshop:product_list" %}" class="btn btn-success">Continue shopping</a>
      {% if cart  %}
      <a href="{% url "orders:order_create" %}" class="btn btn-primary">
      Checkout
      </a>
      {% endif %}



    </p>
    </div>
  </div>


  <div class="container">

    {% if recommended_products %}
			<div class="text-center rp-title">
				<h3>People who bought this also bought</h3>
			</div>

		<div class="row">
			{% for p in recommended_products %}
				<div class="col-lg-3">
					<div class="product-item">
						<figure>
							<a href="{{ p.get_absolute_url }}">
								<img src="{{ p.image.url }}">
							</a>
							<div class="pi-meta">
								<div class="pi-m-left">
									<img src="http://localhost/external-css/img/icons/eye.png" alt="">
									<p>quick view</p>
								</div>
								<div class="pi-m-right">
									<img src="http://localhost/external-css/img/icons/heart.png" alt="">
									<p>save</p>
								</div>
							</div>
						</figure>
						<div class="product-info">
							<h6><a href="{{ p.get_absolute_url }}">{{ p.name }}</a></h6>
							<p>{{p.price}} </p>
							<a href="{{ p.get_absolute_url }} " class="site-btn btn-line hvr-float-shadow">SHOP NOW</a>
						</div>
					</div>
				</div>
				{% endfor %}

			</div>

		{% endif %}
		</div>

  </div>



    {% endblock  %}



    </body>
</html>