myshop/blog/urls.py
from django.urls import path
from . import views

app_name= "blog"

urlpatterns = [
    path("<slug:post_detail>/<int:year>/<int:month>/<int:day>/", views.postdetail, name="post_detail"),
    path("blog", views.postlist, name="blog_news")
]

myshop/cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),

    path('remove/<int:product_id>/', views.cart_remove, 
                                     name='cart_remove'),
                                     
    path('checkout', views.checkout, name='checkout'),
]

myshop/myonlineshop/urls.py
from django.urls import path
from . import views


app_name = 'myonlineshop'

urlpatterns = [
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('selectcurrency', views.selectcurrency, name='selectcurrency'),
    path('', views.index, name='index'),
    # path('', views.home, name='home'),
    path('selectcurrency', views.selectcurrency, name='selectcurrency'),
    path('picture_x', views.picture, name='picture'),
    path('contact', views.contact, name='contact'),
    path('checkout', views.checkout, name='checkout'),
    
    path('categorie', views.categorie, name='categorie'),
    path('search', views.post_search, name='post_search'),
    path('trackorder', views.track, name='track_order'),
    path('store', views.product_list, name='product_list'),
    path('addcomment/<int:id>', views.addcomment, name='addcomment'),
    path('mail', views.popMail, name='mail'),
    #path('addcomment/<int:id>', views.addcomment, name='addcomment'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    


]

myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
     path('currencies/', include('currencies.urls')),
    path('admin/', admin.site.urls),

    path('paystack/', include('paystack.urls', namespace='paystack')),


    path('cart/', include('cart.urls', namespace='cart')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('orders/', include('order.urls', namespace='order')),
    path('account/', include('account.urls')),

    path('payment/', include('payment.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('myonlineshop.urls', namespace='myonlineshop')),

    # path('about/', about),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

myshop/paystack/urls.py
from django.conf.urls import url
from django.views.decorators.csrf import csrf_exempt

from . import settings
from . import views

app_name = 'paystack'

urlpatterns = [
    url(r'^verify-payment/(?P<order>[\w.@+-]+)/$',
        views.verify_payment, name='verify_payment'),
    
    url(r'^failed-verification/(?P<order_id>[\w.@+-]+)/$',
        views.failure_redirect_view, name='failed_verification'),
    url(r'^successful-verification/(?P<order_id>[\w.@+-]+)/$', views.success_redirect_view,name='successful_verification'),
    url(r'^checkout/payment/$', views.payment, name='payment'),
    url(r'^failed-page/$',
        views.TemplateView.as_view(template_name='paystack/failed-page.html'), name='failed_page'),
    url(r'^success-page/$',
        views.success, name='success_page'),
    url(r'^delete/(?P<id>.*)$', views.delete, name='delete-person'),
    url(r'^webhook/$', csrf_exempt(views.webhook_view), name='webhook'),
]

myshop/cart/forms.py
from django import forms
PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 4)]
Size_choice = (
        
        ("None", "None"),
        ('S', 'Small'),
        ('L', 'Large'),
        ('XL', 'Extra Large'),
        ("39", "39"),
        ("40", "40"),
        ("41", "41"),
        ("42", "42")
        

)
class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int)
    override = forms.BooleanField(required=False, initial=False,widget=forms.HiddenInput)
    size_cloth = forms.TypedChoiceField(required=False, choices=Size_choice,  label="Size:", initial='ms')
class CartSizeAddProductForm(forms.Form):
        size_cloth = forms.TypedChoiceField(required=False, choices=Size_choice,  label="Size:", initial='ms')
   

myshop/templates/shop/product/detail.html
{% extends 'shop/base.html' %}
{% load crispy_forms_tags %}

{% load currency %}
{% currency_context %}

{% block content %}
	<!-- Page -->
		<div class="page-area product-page spad" style="margin-top:60px">
			<div class="container">
				<div class="row">
					<div class="col-lg-6">
						<figure>
							<img class="product-big-img" src= "{% if product.image%}{{product.image.url}}{% else %} http://localhost/external-css/img/no_image.png {% endif %}" width="400px" height="500px"  alt="">
						</figure>
						<div class="product-thumbs">
							<div class="product-thumbs-track">



								<div class="pt" data-imgbigurl="{% if product.image%}{{product.image.url}}{% else %} http://localhost/external-css/img/no_image.png {% endif %}"><img src="{% if product.image%}{{product.image.url}}{% else %} http://localhost/external-css/img/no_image.png {% endif %}" alt=""></div>
								<div class="pt" data-imgbigurl="{% if product.slider1%}{{product.slider1.url}}{% else %} http://localhost/external-css/img/no_image.png {% endif %}"><img src="{% if product.slider1%}{{product.slider1.url}}{% else %} http://localhost/external-css/img/no_image.png {% endif %}" alt=""></div>
								<div class="pt" data-imgbigurl="{% if product.slider2%}{{product.slider2.url}}{% else %} http://localhost/external-css/img/no_image.png {% endif %}"><img src="{% if product.slider2%}{{product.slider2.url}}{% else %} http://localhost/external-css/img/no_image.png {% endif %}" alt=""></div>
								<div class="pt" data-imgbigurl="{% if product.slider3%}{{product.slider3.url}}{% else %} http://localhost/external-css/img/no_image.png {% endif %}"><img src="{% if product.slider3%}{{product.slider3.url}}{% else %} http://localhost/external-css/img/no_image.png {% endif %}" alt=""></div>

							</div>
						</div>
					</div>
					<div class="col-lg-6">
						<div class="product-content">
							<h2>{{product.name}} </h2>
							<div class="pc-meta">
								<h4 class="price mb-2">{{ product.price|currency:request.session.currency }} {{ request.session.currency }}</h4>
								<div class="product-rating">
                                    <i class="fa fa-star{% if product.avaregereview < 1%}-o empty{% endif%}"></i>
                                    <i class="fa fa-star{% if product.avaregereview < 2%}-o empty{% endif%}"></i>
                                    <i class="fa fa-star{% if product.avaregereview < 3%}-o empty{% endif%}"></i>
                                    <i class="fa fa-star{% if product.avaregereview < 4%}-o empty{% endif%}"></i>
                                    <i class="fa fa-star{% if product.avaregereview < 5%}-o empty{% endif%}"></i>
                                    {{ product.avaregereview |stringformat:".2f"}}
                                </div>
                                <a href="#3-tab"> {{ product.countreview}}  Review(s) / Add Review</a>
								{% comment %} {% if messages %}
										{% for message in messages %}
											<div class="alert alert-{{ message.tags }}  alert-dismissible fade-show" role="alert">
											{{ message}}
											<button type="button" class="close" data-dismiss="alert">&times;</button>

										</div>
									{% endfor %}

								{% endif %} {% endcomment %}

							</div>




								<form action="{% url "cart:cart_add" product.id %}" method="post">

										{% if product.quantity > 0 %}
										<div id="div_id_quantity" class="form-group"> <label for="id_quantity" class=" requiredField">
												Quantity<span class="asteriskField">*</span> </label>
												<div class="">
													<select name="quantity" class="select form-control" id="id_quantity">
													<option value="1">1</option>
													<option value="2">2</option>
														<option value="3">3</option>

													</select>
												</div>
										</div>
										{% else %}
										<div id="div_id_quantity" class="form-group" style="display:none;">
										<label for="id_quantity" class=" requiredField">
												Quantity<span class="asteriskField">*</span> </label>
												<div class="">
													<select name="quantity" class="select form-control" id="id_quantity" disabled>
													<option value="1">0</option>
													<option value="2">2</option>
														<option value="3">3</option>

													</select>
												</div>
										</div>

										{% endif %}

										<input type="hidden" name="override" value="False" id="id_override">
									<div id="div_id_size_cloth" class="form-group">

											{% if product.variant == 'Size' %}
												<label for="id_size_cloth" class="">
																Size:
												</label>
											<div class="">

												<select name="size_cloth" class="select form-control" id="id_size_cloth">
													{% comment %} <option value="none">None</option> {% endcomment %}
													<option value="S">Small</option>
													<option value="L">Large</option>
													<option value="XL">Extra Large</option>
													<option value="39">39</option>
													<option value="40">40</option>
													<option value="41">41</option>
													<option value="42">42</option>

												</select>
												{% endif %}

											</div>



									</div>


									<div id="div_id_size_cloth" class="form-group">

													{% if product.variant == 'None' %}
														<label for="id_size_cloth" class="">
																		Size:
														</label>
												<div class="">
{% comment %}
														<select name="size_cloth" class="select form-control" id="id_size_cloth">
															<option value="None">None</option>
															<option value="L">Large</option>
															<option value="XL">Extra Large</option>

														</select> {% endcomment %}

																<select name="size_cloth" class="select form-control" id="id_size_cloth">
																<option value="None">None</option>
																{% comment %} <option value="S">Small</option>
																<option value="L">Large</option>
																<option value="XL">Extra Large</option>
																<option value="39">39</option>
																<option value="40">40</option>
																<option value="41">41</option>
																<option value="42">42</option> {% endcomment %}

												</select>
													{% endif %}

												</div>



									</div>

											{% csrf_token %}
											{% if product.quantity > 0 %}
												<input type="submit" value="Add to cart" class="btn btn-warning mb-2">

												{% else %}
													<input type="submit" disabled value="Out of Stock" class="btn btn-danger mb-2">

											{% endif %}

								</form>








											<p><strong>Availability:</strong> {% if product.quantity > 0  %} In Stock {% else %}Currently Out of Stock {% endif %}</p>

											<h4>Category</h4>
											<p>
												<a href="{{ product.category.get_absolute_url}}" class="text-warning">
													{{product.category}}
												</a>
											</p>

						</div>






				</div>


			</div>








				<div class="container">

							<div class="product-details">
								<div class="row">
									<div class="col-lg-10 offset-lg-1">
										<ul class="nav" role="tablist">
											<li class="nav-item">
												<a class="nav-link active" id="1-tab" data-toggle="tab" href="#tab-1" role="tab" aria-controls="tab-1" aria-selected="true">Description</a>
											</li>
											<li class="nav-item">
												<a class="nav-link" id="2-tab" data-toggle="tab" href="#tab-2" role="tab" aria-controls="tab-2" aria-selected="false">Additional information</a>
											</li>
											<li class="nav-item">

												<a class="nav-link" id="3-tab" data-toggle="tab" href="#tab-3" role="tab" aria-controls="tab-3" aria-selected="false">Reviews({{ product.countreview}})</a>

											</li>
										</ul>
										<div class="tab-content">
											<!-- single tab content -->
													<div class="tab-pane fade show active" id="tab-1" role="tabpanel" aria-labelledby="tab-1">
														<p>{{product.description|safe }} </p>
													</div>
													<div class="tab-pane fade" id="tab-2" role="tabpanel" aria-labelledby="tab-2">
														<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit</p>
													</div>


												<div class="tab-pane fade" id="tab-3" role="tabpanel" aria-labelledby="tab-3">


													{% for rs in comments %}
													<div class="col-md-6 mb-3">


															<div class="card">
																<div class="card-body shadow-lg p-3  bg-white rounded">

																	<p>
																		<span class="text-danger"> Review  by</span> {{ rs.user.first_name }} {{ rs.updated }}
																		</p>
																		<p><span class="text-danger"> Subject</span>: {{ rs.subject }} </p>
																		<p><span class="text-danger"> Comment</span>:: {{ rs.comment }} </p>
																		<i class="fa fa-star{% if rs.rate < 1 %}-o empty{% endif %}"></i>
																								<i class="fa fa-star{% if rs.rate < 2 %}-o empty{% endif %}"></i>
																								<i class="fa fa-star{% if rs.rate < 3 %}-o empty{% endif %}"></i>
																								<i class="fa fa-star{% if rs.rate < 4 %}-o empty{% endif %}"></i>
																								<i class="fa fa-star{% if rs.rate < 5 %}-o empty{% endif %}"></i>


																</div>

															</div>



																	{% comment %}
																	{% empty %}

																	<h2>Be the first to Comment</h2> {% endcomment %}
													</div>


													{% endfor %}




													<div class="col-md-6">
																	<h4 class="text-uppercase">Write Your Review</h4>
																			{% if messages %}
																				{% for message in messages %}
																					<div class="alert alert-{{message.tags}}" role="alert">
																						{{ message }}
																					</div>
																				{% endfor %}
																			{% endif %}



																	<form class="review-form" action="/addcomment/{{ product.id }}" method="post">
																		{% csrf_token %}
																		<div class="form-group">
																			<input name="subject" class="form-control" type="text" placeholder="Your subject" />
																		</div>
																		<div class="form-group">
																			<textarea name="comment" class="form-control" placeholder="Your review"></textarea>
																		</div>
																		<div class="form-group">
																			<div class="input-rating">
																				<strong class="text-uppercase">Your Rating: </strong>
																				<div class="stars">
																					<input type="radio" id="star5" name="rate" value="5" /><label for="star5"></label>
																					<input type="radio" id="star4" name="rate" value="4" /><label for="star4"></label>
																					<input type="radio" id="star3" name="rate" value="3" /><label for="star3"></label>
																					<input type="radio" id="star2" name="rate" value="2" /><label for="star2"></label>
																					<input type="radio" id="star1" name="rate" value="1" /><label for="star1"></label>
																				</div>
																			</div>
																		</div>
																		{% if user.id is not None %}
																			<button class="btn btn-success">Submit</button>
																		{% else %}
																			You must be logged in to post a review

																		{% endif %}
																	</form>


													</div>

												</div>
										</div>




									</div>
								</div>
							</div>
				<div>




                    <!--RECOMMEND CODE-->

					<!--{% if recommended_products %}-->
					<!--		<div class="text-center rp-title">-->
					<!--			<h3>People who bought this also bought</h3>-->
					<!--		</div>-->



					<!--		<div class="row">-->
					<!--			{% for p in recommended_products %}-->
					<!--				<div class="col-lg-3">-->
					<!--					<div class="product-item">-->
					<!--						<figure>-->
					<!--							<a href="{{ p.get_absolute_url }}">-->
					<!--								<img src="{{ p.image.url }}">-->
					<!--							</a>-->
					<!--							<div class="pi-meta">-->
					<!--								<div class="pi-m-left">-->
					<!--									<img src="http://localhost/external-css/img/icons/eye.png" alt="">-->
					<!--									<p>quick view</p>-->
					<!--								</div>-->
					<!--								<div class="pi-m-right">-->
					<!--									<img src="http://localhost/external-css/img/icons/heart.png" alt="">-->
					<!--									<p>save</p>-->
					<!--								</div>-->
					<!--							</div>-->
					<!--						</figure>-->
					<!--						<div class="product-info">-->
					<!--							<h6><a href="{{ p.get_absolute_url }}">{{ p.name }}</a></h6>-->
					<!--							<p>{{ product.price|currency:request.session.currency }} {{ request.session.currency }} </p>-->
					<!--							<a href="{{ p.get_absolute_url }} " class="site-btn btn-line hvr-float-shadow">SHOP NOW</a>-->
					<!--						</div>-->
					<!--					</div>-->
					<!--				</div>-->
					<!--				{% endfor %}-->

					<!--		</div>-->


					<!--{% endif %}-->
			</div>
		</div>



	<!-- Page end -->
    {% endblock  %}

myshop/templates/shop/product/search.html
{% extends "shop/base.html" %}
{% load crispy_forms_tags %}
{% block title %}Search{% endblock %}
{% block content %}




<div class="container" style="margin-top:120px; margin-bottom:60px;">
  <div class="row">

    <div class="col-xl-12">
        <div class="card card-body bg-light">

            {% if query %}
                <h2>Product containing "{{ query }}"</h2>
                <h3>
                {% with results.count as total_results %}
                    Found {{ total_results }} result{{ total_results|pluralize }}
                {% endwith %}
                </h3>

            <div class="row mt-3">
             {% for product in results %}

            <div class="card ml-5" style="width: 19rem;">
                 <a href="{{ product.get_absolute_url }}">
                            <img src="{% if product.image %}{{ product.image.url }} {% else %}  http://localhost/external-css/img/no_image.png {% endif %}" class="card-img-top" alt="...">
                        </a>
                <div class="card-body my-product">
                    <h5 class="card-title text-center"><a href="{{ product.get_absolute_url }}" >{{ product.name }}</a></h5>
                    <p class="card-text text-center">${{ product.price }}</p>
                    <p class="text-center"><a href="{{ product.get_absolute_url }} " class="site-btn btn-line">SHOP NOW</a></p>
                </div>
            </div>
             {% empty %}
                <h5 class="ml-3">There are no results for your query.</h5>
            {% endfor %}
             </div>
           
                <h2 class="ml-2 mt-3"><a href="{% url "myonlineshop:post_search" %}">Search again</a></h2>
            {% else %}
                <h2>Search for products</h2>
                <form method="get">
                {{ form|crispy }}
                <input type="submit" class="btn btn-primary btn-lg" value="Search">
                </form>
            {% endif %}
  
        </div>
      </div>
  </div>

</div>      
{% endblock %}

myshop/templates/shop/product/store.html
{% extends 'shop/base.html' %}
{% load currency %}
{% currency_context %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% block title %}Store{% endblock %}
    <link rel="stylesheet" href="http://localhost/external-css/css/navbar.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    
	
    <link rel="stylesheet" href="http://localhost/external-css/css/mystyle.css"/>
    <link rel="stylesheet" href="http://localhost/external-css/css/store-style.css">
	
  </head>
  <body>

    {% block content%}

 <div class="container" style="margin-top:120px; margin-bottom:60px;">

    <div class="row">
      <div class="col-12">
        {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}  alert-dismissible fade-show" role="alert">
            {{ message}}
            <button type="button" class="close" data-dismiss="alert">&times;</button>


  
    
        </div>
  {% endfor %}

{% endif %}
      </div>

      
    </div>
    
    
    <div class="row">
        <div class="col-12">

          
          <div class="jumbotron jumbotron-fluid bg-dark">
            <div class="container">
              <h2 style="text-align:center; color:white;">{% if category %}{{ category.name }}{% else %} COLLECTIONS {% endif %}</h2>
            </div>

          </div>

        </div>


    </div>


    <div class="row mt-4">
     
      <div class="col-xl-3">
          <h3>CATEGORIES</h3>
          <ul class="list-group mt-4 mb-3 my-links">
          
            <li class="list-group-item">
            <a href="{% url "myonlineshop:product_list" %}">All</a>
         
            </li>
            {% for c in categories %}
            <li class="list-group-item">
                <a href="{{ c.get_absolute_url }}">
                {{ c.name }}
                </a>

            </li>
            {% endfor %}
            
          </ul>

      </div>

      <div class="col-xl-9">

          

          <!-- <h3 class="text-center">{% if category %}{{ category.name }}{% else %} COLLECTIONS {% endif %}</h3> -->

          
           <div class="row">
            {% for product in products %}
            <div class="col-sm-6 col-md-6 col-xl-4 col-6 mt-3 my-product">
              <a href="{{ product.get_absolute_url }}">
                  <img src="{% if product.image %}{{ product.image.url }} {% else %}  http://localhost/external-css/img/no_image.png {% endif %}" class="card-img-top" alt="...">
              </a>   
                  <p class="text-center mt-3">{{ product.name }}</p>
                  <h3 class="text-center mt-2 mb-3">{{ product.price|currency:request.session.currency }} {{ request.session.currency }}</h3>
                  <p class="text-center">
                  <a href="{{ product.get_absolute_url }} " class="site-btn btn-line hvr-float-shadow">SHOP NOW</a>
                  </p>
                  

            </div>
            {% endfor %}
            
            

          </div>
          
      </div>
    </div>
    <div class="row">

      <div class="col-5">

      </div>

      <div class="col-7 mt-5">
     
        {% include "pagination.html" with page=products %}
        
     
      </div>

    </div>


  </div>


  

                
         {% endblock  %}
  </body>
</html>

myshop/templates/shop/product/test.html
{% extends 'shop/base.html' %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title></title>
    <link rel="stylesheet" href="http://localhost/external-css/css/navbar.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    
	
    <link rel="stylesheet" href="http://localhost/external-css/css/mystyle.css"/>
	
  </head>
  <body>

    {% block content%}
    	

        <div class="first-section" style="margin-top:120px;">
            <div class="container">
                <div class="row mt-4 mb-4">
                    <div class="col-xl-3 category">
                        <h2>Categories</h2>
                        <ul style="list-style:none">
                            <li {% if not category %}class="selected"{% endif %}>
                                <a href="{% url "myonlineshop:product_list" %}" class="btn btn-success mb-3" style="color:white;">All</a>
                            </li>
                        {% for c in categories %}
                            <li {% if category.slug == c.slug %}class="selected"
                                {% endif %}>
                                <a href="{{ c.get_absolute_url }}" class="btn btn-success mb-3" style="color:white;">{{ c.name }}</a>
                            </li>
                        {% endfor %}
                        </ul>

                    </div>

                    <div class="col-xl-9">
                        <h2 class="text-center">{% if category %}{{ category.name }}{% else %} Products {% endif %}</h2>
                        
                        <div class="row">
                        {% for product in products %}
                                <div class="col-sm-6 col-md-6 col-xl-4 col-6">
                                    
                                <div class="card shadow-sm mt-3 cards">
                                
                                    
                                    
                                    <a href="{{ product.get_absolute_url }}">
                                        <img src="{% if product.image %}{{ product.image.url }} {% else %}  http://localhost/external-css/img/no_image.png {% endif %}" class="card-img-top" alt="...">
                                
                                    <div class="card-body ">
                                        <p class="pt-2 card-title bg-primary text-center pb-3">
                                            <a href="{{ product.get_absolute_url }} " style="color:white; font-size:20px">{{ product.name }}</a>
                                        </p>
                                        <p class="pt-2 text-center bg-success pb-3" style="color:white;">
                                            ${{ product.price }}
                                        </p>
                                    </div>
                                
                                </div>
                                
                            </div>

                        {% endfor %}
                        
                        </div>

                                
                    </div>

                        
                </div>
            </div>

        </div>



 <div class="container">
    <div class="row mt-4">
      <div class="col-xl-3">
          <h3>CATEGORIES</h3>
          <ul class="list-group mt-4 mb-3">
          
            <li {% if not category %} class="list-group-item active"{% endif %}>
            <a href="{% url "myonlineshop:product_list" %}" style="color:white;" >All</a>
         
            </li>
            {% for c in categories %}
            <li class="list-group-item">Cloth</li>
            
          </ul>

      </div>

      <div class="col-xl-9">



          <h3 class="text-center push-down">PRODUCTS</h3>
            <div class="row">
            <div class="col-sm-6 col-md-6 col-xl-4 col-6 mt-3 my-product">
                <img src="img\Mens-Standard-Fit-Crew-T-Shirt01-600x764.jpg" class="card-img-top" alt="">
                <p class="text-center mt-3">RED SHIRT</p>
                <h3 class="text-center">$15000</h3>
                <p class="text-center">
                <a href="#" class="site-btn btn-line">SHOP NOW</a>
                </p>

            </div>

            <div class="col-sm-6 col-md-6 col-xl-4 col-6 mt-3 my-product">
                <img src="img\Mens-Standard-Fit-Crew-T-Shirt01-600x764.jpg" class="card-img-top" alt="">
                <p class="text-center mt-3">RED SHIRT</p>
                <h3 class="text-center">$15000</h3>
                <p class="text-center">
                <a href="#" class="site-btn btn-line">SHOP NOW</a>
                </p></a>

            </div>

            <div class="col-sm-6 col-md-6 col-xl-4 col-6 mt-3 my-product">
                <img src="img\Mens-Standard-Fit-Crew-T-Shirt01-600x764.jpg" class="card-img-top" alt="">
                <p class="text-center mt-3">RED SHIRT</p>
                <h3 class="text-center">$15000</h3>
                <p class="text-center">
                <a href="#" class="site-btn btn-line">SHOP NOW</a>
                </p>

            </div>

            <div class="col-sm-6 col-md-6 col-xl-4 col-6 mt-3 my-product">
                <img src="img\Mens-Standard-Fit-Crew-T-Shirt01-600x764.jpg" class="card-img-top" alt="">
                <p class="text-center mt-3">RED SHIRT</p>
                <h3 class="text-center">$15000</h3>
                <p class="text-center">
                <a href="#" class="site-btn btn-line">SHOP NOW</a>
                </p>

            </div>

            <div class="col-sm-6 col-md-6 col-xl-4 col-6 mt-3 my-product">
                <img src="img\5.jpg" class="card-img-top" alt="">
                <p class="text-center mt-3">RED SHIRT</p>
                <h3 class="text-center">$15000</h3>
                <p class="text-center">
                <a href="#" class="site-btn btn-line">SHOP NOW</a>
                </p>

            </div>

          </div>
      </div>
    </div>
  </div>

                
            {% endblock  %}
  </body>
</html>