myshop/blog/urls.py
from django.urls import path
from . import views

app_name= "blog"

urlpatterns = [
    path("<slug:post_detail>/<int:year>/<int:month>/<int:day>/", views.postdetail, name="post_detail"),
    path("blog", views.postlist, name="blog_news")
]

myshop/cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),

    path('remove/<int:product_id>/', views.cart_remove, 
                                     name='cart_remove'),
                                     
    path('checkout', views.checkout, name='checkout'),
]

myshop/myonlineshop/urls.py
from django.urls import path
from . import views


app_name = 'myonlineshop'

urlpatterns = [
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('selectcurrency', views.selectcurrency, name='selectcurrency'),
    path('', views.index, name='index'),
    # path('', views.home, name='home'),
    path('selectcurrency', views.selectcurrency, name='selectcurrency'),
    path('picture_x', views.picture, name='picture'),
    path('contact', views.contact, name='contact'),
    path('checkout', views.checkout, name='checkout'),
    
    path('categorie', views.categorie, name='categorie'),
    path('search', views.post_search, name='post_search'),
    path('trackorder', views.track, name='track_order'),
    path('store', views.product_list, name='product_list'),
    path('addcomment/<int:id>', views.addcomment, name='addcomment'),
    path('mail', views.popMail, name='mail'),
    #path('addcomment/<int:id>', views.addcomment, name='addcomment'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    


]

myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
     path('currencies/', include('currencies.urls')),
    path('admin/', admin.site.urls),

    path('paystack/', include('paystack.urls', namespace='paystack')),


    path('cart/', include('cart.urls', namespace='cart')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('orders/', include('order.urls', namespace='order')),
    path('account/', include('account.urls')),

    path('payment/', include('payment.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('myonlineshop.urls', namespace='myonlineshop')),

    # path('about/', about),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

myshop/order/urls.py
from django.urls import path
from . import views
# from paystack.views import delete_order
app_name = 'orders'
urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    # path('myorder/<int:id>/<int:user_id>/', views.my_order, name='my_order'),
    path('allorders/', views.all_orders, name='all_order'),
    path('orderitem/<int:product_id>/<int:quantity>/<int:order_id>/<int:user_id>/', views.my_order, name='order_item'),
    path('admin/order/<int:order_id>/<int:user_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/',views.admin_order_pdf, name='admin_order_pdf'),
    path('delete/<int:id>/', views.delete, name='delete-person'),
    # path('deleteorder/<int:id>', views.delete_order, name='user_deleteorder'),
]

myshop/paystack/urls.py
from django.conf.urls import url
from django.views.decorators.csrf import csrf_exempt

from . import settings
from . import views

app_name = 'paystack'

urlpatterns = [
    url(r'^verify-payment/(?P<order>[\w.@+-]+)/$',
        views.verify_payment, name='verify_payment'),
    
    url(r'^failed-verification/(?P<order_id>[\w.@+-]+)/$',
        views.failure_redirect_view, name='failed_verification'),
    url(r'^successful-verification/(?P<order_id>[\w.@+-]+)/$', views.success_redirect_view,name='successful_verification'),
    url(r'^checkout/payment/$', views.payment, name='payment'),
    url(r'^failed-page/$',
        views.TemplateView.as_view(template_name='paystack/failed-page.html'), name='failed_page'),
    url(r'^success-page/$',
        views.success, name='success_page'),
    url(r'^delete/(?P<id>.*)$', views.delete, name='delete-person'),
    url(r'^webhook/$', csrf_exempt(views.webhook_view), name='webhook'),
]

myshop/templates/shop/base.html
{% load currency %}
{% load tawkto_tags %}
{% load crispy_forms_tags %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/css/bootstrap.min.css" integrity="sha384-VCmXjywReHh4PwowAiWNagnWcLhlEJLA5buUprzK8rxFgeH0kww/aWY76TfkUoSX" crossorigin="anonymous">
</head>
<body>
   	<meta charset="UTF-8">
	<meta name="description" content="The Plaza eCommerce Template">
	<meta name="keywords" content="plaza, eCommerce, creative, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Favicon -->
	<link href="http://localhost/external-css/img/favicon.ico" rel="shortcut icon"/>

	<!-- Google Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Raleway:400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

	<!-- Stylesheets -->
	<link rel="stylesheet" href="https://tishman2299.000webhostapp.com/external-css/css/bootstrap.min.css"/>
	<link rel="stylesheet" href="https://tishman2299.000webhostapp.com/external-css/css/font-awesome.min.css"/>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="https://tishman2299.000webhostapp.com/external-css/css/owl.carousel.css"/>
	<link rel="stylesheet" href="https://tishman2299.000webhostapp.com/external-css/css/style.css"/>
	<link rel="stylesheet" href="https://tishman2299.000webhostapp.com/external-css/css/animate.css"/>
	<link rel="stylesheet" href="https://tishman2299.000webhostapp.com/external-css/css/store-style.css">
	<link rel="stylesheet" href="https://tishman2299.000webhostapp.com/external-css/css/rating.css">
	<link rel="stylesheet" href="https://tishman2299.000webhostapp.com/external-css/css/hover.css" rel="stylesheet" media="all">>
	{% comment %} <link rel="stylesheet" href="https://tishman2299.000webhostapp.com/external-css/css/message.css"> {% endcomment %}
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">



	<!--[if lt IE 9]>
	  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->



</head>
<body>


	<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>



	<!-- Header section -->

	<header class="header-section">
		<div class="container-fluid">
			<!-- logo -->
			<div class="site-logo">
				<!-- <a href="/home">
				<img src="https://tishman2299.000webhostapp.com/external-css/img/logo.png" alt="logo">
				</a> -->

				<h3><a href="/" style="color:rgb(255,193,7); padding-left:-8px;">TISHR</a></h3>
			</div>
			<!-- responsive -->
			<div class="nav-switch">
				<i class="fa fa-bars"></i>
			</div>
			<div class="header-right">
				<a href="{% url "cart:cart_detail" %}" class="card-bag"><img src="https://tishman2299.000webhostapp.com/external-css/img/icons/bag.png" alt="">
					<span>

						{% with total_items=cart|length %}
						{% if total_items > 0 %}


							{{ total_items }}


						{% else %}
							0
						{% endif %}
						{% endwith %}
					</span>
				</a>
				<a href="/search" class="search"><img src="https://tishman2299.000webhostapp.com/external-css/img/icons/search.png" alt=""></a>&nbsp;&nbsp;<br>
				{% comment %} <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#myModal">
					<img src="https://tishman2299.000webhostapp.com/external-css//img/icons/money1.png" alt="">
				  </button> {% endcomment %}

				  <form id="currency_switcher" method="POST" action="{% url 'myonlineshop:selectcurrency' %}" style="padding-top:8px;">
					{% csrf_token %}
					<select name="currency" onchange="submit()" class="custom-select custom-select-md">
						{% for curr in CURRENCIES %}
							<option value="{{ curr.code }}"
									{% ifequal curr.code request.session.currency %}selected="selected"{% endifequal %}>
									{{ curr.code }} {{ curr.symbol }}
							</option>
						{% endfor %}
					</select>

					<noscript>
						<input type="submit" value="Set" />
					</noscript>

				</form>









			</div>
			<!-- site menu -->

			<ul class="main-menu">
				<li><a href="/">Home</a></li>
				<li><a href="/store">Collections</a></li>
				<li class="dropdown"><a href="javascript:void(0)" class="dropbtn">Categories</a>
				 <div class="dropdown-content">
					<a href="{% url "myonlineshop:product_list" %}" style="color:black">All</a>
					{% for c in categories %}
					<a href="{{ c.get_absolute_url }}" style="color:black">{{c.slug }}</a>

					{% endfor %}
				</div>
				</li>
				<li><a href="/contact">Contact</a></li>
				{% if request.user.is_authenticated %}
				<li  class="dropdown"><a href="{% url "dashboard" %}"  class="dropbtn">Dashboard</a>
				<div class="dropdown-content">
					<a href="{% url "edit" %}" style="color:black">Edit Account</a>
					<a href="{% url "orders:all_order" %}" style="color:black">Orders</a>
					<a href="{% url "myonlineshop:track_order" %}" style="color:black">Track order</a>


				</div>

				</li>
				<li><a href="{% url "logout" %}">Logout</a></li>
				{% else %}
				<li><a href="{% url "login" %}">Login/Signup</a></li>
				{% endif %}

				<li>


				</li>


			</ul>
		</div>
	</header>
	<!-- Header section end -->









    {% block content %}
    {% endblock %}







	<!-- Footer top section -->
	<section class="footer-top-section home-footer">
		<div class="container">
			<div class="row">


				<div class="col-lg-3 col-md-4 col-sm-6">
					<div class="footer-widget">
						<h6 class="fw-title">More info</h6>
						<ul>
							<li><a href="#">Partners</a></li>
							<li><a href="{% url "blog:blog_news" %}">Bloggers</a></li>
							<li><a href="#">Support</a></li>
							<li><a href="#">Terms of Use</a></li>
							{% tawkto_script user_name=request.user user_email=request.user.email %}

						</ul>
					</div>
				</div>
				<div class="col-lg-3 col-md-4 col-sm-6">
					<div class="footer-widget">
						<h6 class="fw-title">Shipping & returns</h6>
						<ul>
							<li><a href="#">About Us</a></li>
							<li><a href="#">Track Orders</a></li>
							<li><a href="#">Returns</a></li>
							<li><a href="#">Shipping</a></li>
							{% comment %} <li><a href="#">Blog</a></li> {% endcomment %}
						</ul>
					</div>
				</div>
				<div class="col-lg-3 col-md-4 col-sm-6">
					<div class="footer-widget">
						<h6 class="fw-title">Contact</h6>
						<div class="text-box">
							<p><span class="icon-footer"><img src="https://tishman2299.000webhostapp.com/external-css/img/enterprise.png"></span> Tishman Ltd </p>
							<p>5, arowolo street beach rd Agric, Ikorodu. </p>
							<p>+234 8141 635443</p>
							<p>info@tishman.com.ng</p>
						</div>
					</div>
				</div>

					<div class="col-lg-3 col-md-4 col-sm-6">
					<div class="footer-widget">
						<h6 class="fw-title">Stay Connected</h6>
						<p class="text-center">Join our mail list to get exclusive offers</p>

				<form method="post" action="/mail">


		 <div id="div_id_email" class="form-group"> <label for="id_email" class=" requiredField" style="color:white;">
                Email<span class="asteriskField">*</span> </label> <div class=""> <input type="email" name="email" maxlength="254" class="emailinput form-control" required id="id_email"> </div> </div>

							{% csrf_token %}
							<input type="submit" class="btn btn-danger" value="Join Newslatter">

						</form>
					</div>
				</div>

			</div>
		</div>
	</section>
	<!-- Footer top section end -->

		<!-- Footer section -->
	<footer class="footer-section">
		<div class="container">
			<p class="copyright text-center">
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
</p>
		</div>

 </footer>


<!-- modal -->
<div class="modal fade" id="myModal">
<div class="modal-dialog modal-sm">
	<div class="modal-content">

	 Modal Header
	<div class="modal-header">
		<h4 class="modal-title">CHANGE CURRENCY</h4>
		<button type="button" class="close" data-dismiss="modal">&times;</button>
	</div>

	{% comment %} <!-- Modal body -->
		<div class="modal-body">
			<form id="currency_switcher" method="POST" action="{% url 'myonlineshop:selectcurrency' %}">
				{% csrf_token %}
				<select name="currency" onchange="submit()" class="custom-select custom-select-md">
					{% for curr in CURRENCIES %}
						<option value="{{ curr.code }}"
								{% ifequal curr.code request.session.currency %}selected="selected"{% endifequal %}>
							{{ curr.symbol }} {{ curr.name }}
						</option>
					{% endfor %}
				</select>

				<noscript>
					<input type="submit" value="Set" />
				</noscript>

			</form>
			</div>

	<div class="modal-footer">
		<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
	</div>

	</div>
</div>
</div> {% endcomment %}


	<!-- Footer section end -->


<!--====== Javascripts & Jquery ======-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>



<script src="https://tishman2299.000webhostapp.com/external-css/js/bootstrap.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://tishman2299.000webhostapp.com/external-css/js/owl.carousel.min.js"></script>
<script src="https://tishman2299.000webhostapp.com/external-css/js/mixitup.min.js"></script>
<script src="https://tishman2299.000webhostapp.com/external-css/js/sly.min.js"></script>
<script src="https://tishman2299.000webhostapp.com/external-css/js/jquery.nicescroll.min.js"></script>
<script src="https://tishman2299.000webhostapp.com/external-css/js/main.js"></script>
<!-- <script src="https://tishman2299.000webhostapp.com/external-css/js/myjs.js"></script> -->

</body>
</html>